CREATE DATABASE IF NOT EXISTS `CENT_DB2`
USE `CENT_DB2`;


--
-- Table structure for table `STUDENT`
--


DROP TABLE IF EXISTS `STUDENT`
CREATE TABLE `STUDENT` (
`STUDENT_ID` INTEGER,
`STUDENT_NAME` VARCHAR,
`STUDENT_SECOND_NAME` VARCHAR,
`STUDENT_AGE` VARCHAR,
`STUDENT_ROLL` VARCHAR,
`STUDENT_MOTHER` VARCHAR,
`STUDENT_FATHER` VARCHAR,
PRIMARY KEY (`STUDENT_ID`)
);


--
-- Table structure for table `MOVIES`
--


DROP TABLE IF EXISTS `MOVIES`
CREATE TABLE `MOVIES` (
`ID` INTEGER,
`NAME` VARCHAR,
`YEAR` VARCHAR,
PRIMARY KEY (`ID`)
);


--
-- Dumping data for table `STUDENT`
--

LOCK TABLES `STUDENT` WRITE;
INSERT INTO `STUDENT` VALUES ('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR'),('ABCD','XYZ','7','23','SADHNA','MAHAVIR');
UNLOCK TABLES;

--
-- Dumping data for table `MOVIES`
--

LOCK TABLES `MOVIES` WRITE;
INSERT INTO `MOVIES` VALUES ('BirdCommonName1','BirdScientificName1'),('BirdCommonName2','BirdScientificName2'),('BirdCommonName3','BirdScientificName3');
UNLOCK TABLES;